version: "3"
services:
  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/var/www/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - executer
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx_log:/var/log/nginx  # Output log to host
    links:
      - webapp
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    command: nginx -c /etc/nginx/nginx.conf

  executer:
    # only for build
    build: ./executer
    command: echo "shellgei executer already initialized"

volumes:
  images_tmp:
    driver: local

https-portal:
  environment:
    STAGE: local
    DOMAINS: 'http://www.shellgei-web.net'
