version: "3"
services:
  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/var/www/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - executer
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx_log:/var/log/nginx  # Output log to host
    links:
      - webapp
    environment:
      TZ: "Asia/Tokyo"
    command: nginx -c /etc/nginx/nginx.conf

  executer:
    # only for build
    build: ./executer
    command: echo "shellgei executer already initialized"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - nginx
    environment:
      STAGE: local
      #STAGE: production
      DOMAINS: 'localhost -> http://nginx:80'
      #DOMAINS: 'shellgei-web.net -> http://nginx:80'

volumes:
  images_tmp:
    driver: local

